services:
  - type: web
    name: content-genius-backend
    rootDir: backend-dotnet/BackendAPI
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_RUNNING_IN_CONTAINER
        value: "true"
